version: '3.8'

services:
  # FastAPI приложение
  app:
    build: .
    container_name: fileserver_app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app:ro  # Монтируем файлы только для чтения
    networks:
      - fileserver_network
    depends_on:
      - nginx

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: fileserver_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - fileserver_network
    env_file:
      - docker.env

networks:
  fileserver_network:
    driver: bridge

volumes:
  nginx_logs:
